CREATE TABLE records(id INTEGER PRIMARY KEY AUTOINCREMENT, uuid TEXT NOT NULL, timestamp DATETIME NOT NULL);
CREATE TABLE measurements(id INTEGER PRIMARY KEY AUTOINCREMENT, record_id INTEGER NOT NULL, circuit TEXT NOT NULL, value FLOAT NOT NULL, FOREIGN KEY (record_id) REFERENCES records(id));
