CREATE TABLE records(id INTEGER PRIMARY KEY AUTOINCREMENT, uuid TEXT NOT NULL, duration FLOAT NOT NULL, timestamp DATETIME NOT NULL);
CREATE TABLE measurements(id INTEGER PRIMARY KEY AUTOINCREMENT, record_id INTEGER NOT NULL, circuit TEXT NOT NULL, amperage FLOAT NOT NULL, voltage FLOAT NOT NULL, FOREIGN KEY (record_id) REFERENCES records(id) ON DELETE CASCADE);
CREATE INDEX records_timestamp ON records(timestamp);
